services:
  app:
    container_name: k-mlw-worker-1
    build: .
    ports:
      - "5823:5823"
    environment:
      - PORT=5823
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
    restart: always

  redis:
    container_name: k-mlw-redis-1
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
