services:
  ktv-server:
    container_name: k-mlw-worker-1
    # build: . 不需要build,因为直接用ghcr的image
    image: ghcr.io/birchtree2/ktv-song-web:latest
    ports:
      - "5823:5823"
    environment:
      - PORT=5823
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
    restart: always

  redis:
    container_name: k-mlw-redis-1
    image: redis:alpine
    # 为了防止已有redis服务的影响，不向外暴露端口
    # 如果需要在主机访问这个redis，把下面的注释删除
    # ports:
    #  - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
